### ISSUE TITLE
Asking about: Headache

### ISSUE THREAD

**Issue by rodrigofegui** [rodrigofegui/IA-proj2#6]
## Description
Translate the following table into fuzzy logic with **sets**, **rules** and **humanized questions** to ask to patients. All these aspect are related to headache

| Aspect    | Dengue      | Zika        | Chikungunya |
|-------------|-------------|-------------|-------------|
| Occurence and intensity | +++ | ++ | ++ |

## Acception criteria
- [x] Create antecendents
- [x] Create rules
- [x] Create humanized questions

**Comment by gust-luiz** [comment]
Task **Create antecendents** solved on commit https://github.com/rodrigofegui/IA-proj2/commit/ced10b752650a170bfc99f0779799e2cdd2cf8eb

**Comment by gust-luiz** [comment]
Taks **Create rules** solved on commit 0cabc9df1a9370b5aa5863236163b9775517c103

**Comment by gust-luiz** [comment]
Task **Create humanized questions** solved on commit c5a08b1f5ed1cf4747be82421904c951b971a203
