### ISSUE TITLE
Asking about: itch

### ISSUE THREAD

**Issue by rodrigofegui** [rodrigofegui/IA-proj2#7]
## Description
Translate the following table into fuzzy logic with **sets**, **rules** and **humanized questions** to ask to patients. All these aspect are related to itch.

| Aspect    | Dengue      | Zika        | Chikungunya |
|-------------|-------------|-------------|-------------|
| Intensity | mild | moderate/intense | mild |

## Acception criteria
- [x] Create antecendents
- [x] Create rules
- [x] Create humanized questions

**Comment by gust-luiz** [comment]
Task **Create antecedents** solved in commit 57e080d26aa0b88bd43084767eb15456abbd5e68

**Comment by gust-luiz** [comment]
Task **Create rules** solved in commit c2f0637c3a64a0d731e08c92c1f8c6b9d4222047

**Comment by gust-luiz** [comment]
Task **Create humanized questions** solved in commit 4748425aea9182b9dcc30ae62b0666033d051b79
