### ISSUE TITLE
Asking about: ganglionic hypertrophy

### ISSUE THREAD

**Issue by rodrigofegui** [rodrigofegui/IA-proj2#8]
## Description
Translate the following table into fuzzy logic with **sets**, **rules** and **humanized questions** to ask to patients. All these aspect are related to ganglionic hypertrophy (swelling in the neck).

| Aspect    | Dengue      | Zika        | Chikungunya |
|-------------|-------------|-------------|-------------|
| Occurence | mild | intense | moderate |

## Acception criteria
- [x] Create antecendents
- [x] Create rules
- [x] Create humanized questions

**Comment by gust-luiz** [comment]
Task **Create antecedents** solved in commit 291e7dbfcb7f90d0873fccd8a5cf465adfca7449

**Comment by gust-luiz** [comment]
Task **Create rules** solved in commit 6065b254eb88906750828fbbeeed3b8c999148f8

**Comment by gust-luiz** [comment]
Task **Create humanized questions** solved in commit 541665e91ac9d5b338e994488df2423f9726c722
