### ISSUE TITLE
Asking about: hemorrhagic dyscrasia

### ISSUE THREAD

**Issue by rodrigofegui** [rodrigofegui/IA-proj2#9]
## Description
Translate the following table into fuzzy logic with **sets**, **rules** and **humanized questions** to ask to patients. All these aspect are related to hemorrhagic dyscrasia ([tendency to bleeding for no apparent reason (spontaneous bleeding) or more intense or prolonged bleeding after trauma.](https://pt.wikipedia.org/wiki/Di%C3%A1tese_hemorr%C3%A1gica))

| Aspect    | Dengue      | Zika        | Chikungunya |
|-------------|-------------|-------------|-------------|
| Occurence | moderate | none | mild |

## Acception criteria
- [x] Create antecendents
- [x] Create rules
- [x] Create humanized questions

**Comment by gust-luiz** [comment]
Task **Create antecedents** solved in commit 955fb020698267804cd9b30eea339225f28af760

**Comment by gust-luiz** [comment]
Task **Create rules** solved in commit 653f78dd75f211b6fdf2b2cfbb9588391dbe33ab

**Comment by gust-luiz** [comment]
Task **Create humanized questions** solved in commit 102b923d6aacf72d32d547ac2bf924a15cdef86f
